- .gitignore
- api/templates/dev-robots.txt
- api/templates/robots.txt
- api/views.py
- pyconkr/urls.py
이전 홈페이지 코드 참고하여, templates 에 robots.txt 를 넣고 template_render 방식을 사용했습니다.
graphql 로 처리하도록 하고 싶은데, 좋은 방법이 있다면 제안해주세요~
> Add robots.txt

- .github/CONTRIBUTING.md
- README.md
README를 다듬고 CONTRIBUTION 가이드를 추가했습니다
> README를 다듬고 CONTRIBUTION 가이드를 추가했습니다

- api/oauth_tokenbackend.py
- requirements.txt
naver 로그인을 추가하였습니다.
Thank you ❤️
> Support naver and upgrade pyyaml to avoid security ararm

- api/models/program.py
- api/schemas/presentation.py
- api/schemas/user.py
- api/tests/scheme/presentation_queries.py
- api/tests/scheme/test_presentation.py
- api/tests/scheme/test_user.py
- api/tests/scheme/user_queries.py
> CFP API와 User 동의 API 추가하고 테스트 케이스 작성했습니다.

- api/admin.py
- api/schemas/sponsor.py
- api/tests/scheme/test_sponsor.py
- 후원사 제안이력이 없을 경우 None 반환, 
- admin페이지 필터 추가
Thank you ❤️
> 후원사 제안이력이 없을 경우 None 반환, admin페이지 필터 추가

- pyconkr/tests.py
- pyconkr/utils.py
- [*] PR의 **compare branch를 master나 develop로 생성하지 않아야** 합니다. :smile:
- [*] PR의 **base branch는 develop으로 지정**해야 합니다.
- [*] Commit Message가 적절한지 확인해주세요
- [*] Lint나 Unit Test가 통과했는지 확인해주세요
- [*] 가급적이면 테스트 케이스를 작성해주세요
특정한 파일에 허가된 이메일 설정을 settings 에 주입합니다.
Thank you ❤️
> add pyconkr.utils.load_permitted_settings_from_ini

- requirements.txt
> fix security alerts

- .pylintrc
> change pylint max-line-length=120

- pyconkr/settings.py
- requirements.txt
- django-constance 를 추가합니다.
- 기본적인 setting 을 만들고 잘 동작함을확인했습니다. 
Thank you ❤️
> add django-constance

- api/migrations/0040_auto_20190427_2028.py
- api/migrations/0041_auto_20190427_2033.py
- api/migrations/0042_copy_proposal_field_to_presentation.py
- api/models/program.py
- api/tests/scheme/test_review.py
> 버그 픽스 버전 릴리즈합니다.

- api/models/sponsor.py
- api/schemas/sponsor.py
- api/tests/scheme/test_sponsor.py
- locale/en/LC_MESSAGES/django.po
- locale/ko/LC_MESSAGES/django.po
Accept에도 자리를 홀딩하는 것으로 알고리즘 변경
Thank you ❤️
> Accept에도 자리를 홀딩하는 것으로 알고리즘 변경

- api/schemas/sponsor.py
- api/tests/scheme/sponsor_queries.py
> 후원사 등급 쿼리에 잔여 좌석 수를 추가했습니다

- .pylintrc
- ticket/schemas.py
- ticket/test_ticket.py
- ticket/ticket_queries.py
ticket 단일 조회 함수 추가하였습니다
Thank you ❤️
> 티켓 상세 내역 단일 조회 함수 추가

- api/schemas/user.py
- api/tests/scheme/test_user.py
- api/tests/scheme/user_queries.py
- locale/en/LC_MESSAGES/django.po
- locale/ko/LC_MESSAGES/django.po
개인 후원 API를 추가하였습니다.
Thank you ❤️
> 개인 후원 API 추가

- docker-entrypoint.sh
- ticket/admin.py
> 얼리버드 티켓 환불을 위해 어드민 기능 추가합니다 

- .circleci/config.yml
- docker-compose.yml
- pyconkr/production_settings.py
- pyconkr/staging_settings.py
- ticket/admin.py
- ticket/models.py
- ticket/schemas.py
- ticket/test_ticket.py
> 디비 이전을 위한 릴리즈

- docker-entrypoint.sh
> Comment database

- pyconkr/backends.py
- pyconkr/settings.py
django email 설정을 추가합니다.
constance 정보를 사용하기 위해 email backend 를 새로 생성 후 사용했으며 이 PR이 머지된 이후에 실제 메일 발송할 수 있도록 코드 넣을 예정입니다.
> Add django email setting with custom email backend with constance

- pyconkr/production_settings.py
- pyconkr/settings.py
- pyconkr/staging_settings.py
- requirements.txt
> Add sentry logging

- ticket/admin.py
> Ticket admin 버그 수정

- ticket/admin.py
> [얼리버드 티켓 판매 현황 파악용] 프로덕트별 잔여 티켓 수 추가

- ticket/admin.py
> Add ticket export feature

- api/oauth_tokenbackend.py
- api/tests/oauth_app_response.py
- api/tests/test_oauth_backend.py
> 이메일이 없을 경우에 대한 에러 처리 추가

- api/schemas/presentation.py
- api/tests/scheme/presentation_queries.py
- api/tests/scheme/test_presentation.py
통과된 발표 목록을 반환하는 API 입니다.
Thank you ❤️
> Accepted=True 인 발표 목록을 반환하는 api 작성

- api/admin.py
- api/schemas/presentation.py
> 영문 발표 내용 수정을 위한 패치입니다

- api/schemas/tutorial.py
- api/schemas/user.py
- api/tests/scheme/test_user.py
> 일부 API에서 내용이 없는 field에 alter data를 사용하도록 반영

- ticket/admin.py
- ticket/schemas.py
- ticket/test_ticket.py
> 환불 기능을 개선하였습니다

- requirements.txt
> fix security alert

- ticket/admin.py
> Add filter into ticket product

- ticket/admin.py
> 제품 export 기능 추가

- api/admin.py
- ticket/schemas.py
> 무료 티켓 환불 버그 수정

- ticket/admin.py
- ticket/schemas.py
> 어드민에서 무료 티켓 환불 가능하도록 수정

- api/admin.py
> Add creattor autocomplete_field option

- api/admin.py
> OAuth export/import 추가

- api/admin.py
- api/schemas/presentation.py
- api/schemas/user.py
- api/urls.py
- pyconkr/urls.py
- ticket/admin.py
- ticket/templates/issue.html
- ticket/views.py
> 튜토리얼 환불 기한을 시작 전까지로 하는 기능과 발표자 등록 여부 확인 기능 배포

- api/schemas/lightningtalk.py
- ticket/admin.py
- ticket/models.py
> 등록 기능 버그 수정
